name: publish

on:
  workflow_dispatch:

jobs:
  properties:
    # Read gradle.properties and get snapshot property
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: lol
        run: |
          echo "snapshot=$(grep '^snapshot=' gradle.properties | cut -d'=' -f2)"
          echo "minecraft_version=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)"
      - name: read gradle.properties
        id: gradle-properties
        run: |
          echo "snapshot=$(grep '^snapshot=' gradle.properties | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"
          echo "minecraft_version=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"
  build:
    needs: properties
    strategy:
      fail-fast: false
      matrix:
        loader:
          - name: fabric
            formatted: Fabric
          - name: neoforge
            formatted: NeoForge
        exclude:
          - loader:
              name: ${{ needs.properties.outputs.snapshot == 'true' && 'neoforge' }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: lol2
        run: echo ${{ needs.properties.outputs.snapshot == 'true' }}
